### PR TITLE
readme from markdown to rst

### PR DESCRIPTION
**Pull request by juanpabloaj**
Pypi use rst readme files.

### CODE REVIEW

**Comment by noajshu** [comment]
Thanks!

**Comment by noajshu** [comment]
I've submitted to Pypi [here](https://pypi.python.org/pypi?name=sidomo&version=0.0.1&:action=display) but it's not showing up in search results or with `pip search sidomo`
I'm new to Pypi, do you know why this might be failing?

**Comment by juanpabloaj** [comment]
maybe you need add the license or the classifiers in the setup file, you can use this setup like a example

https://github.com/juanpabloaj/pip-init/blob/master/setup.py

**Comment by juanpabloaj** [comment]
this is a good post about of share packages with pypi

https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/

**Comment by juanpabloaj** [comment]
BTW for update the readme or the package in pypi you need update the version number in the setup file

**Pull request merged**
